# generated by datamodel-codegen:
#   filename:  agent-event.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Status(StrEnum):
    running = 'running'
    done = 'done'
    error = 'error'


class StepEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['step']
    seq: int = Field(..., ge=0)
    id: str
    label: str
    status: Status


class TextEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['text']
    seq: int = Field(..., ge=0)
    blockId: str
    delta: str
    unsupported: bool | None = Field(
        None,
        description='Claim without any valid citation; the UI flags it instead of hiding it.',
    )


class Kind(StrEnum):
    berkas = 'berkas'
    akta = 'akta'
    person = 'person'
    company = 'company'
    document = 'document'
    checklist = 'checklist'
    schedule = 'schedule'
    legal = 'legal'
    repertorium = 'repertorium'
    klapper = 'klapper'


class CitationTarget(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind
    id: UUID
    label: str
    href: str
    field: str | None = Field(
        None, description='Field to highlight, e.g. nik or address.'
    )


class Tone(StrEnum):
    ok = 'ok'
    warn = 'warn'
    bad = 'bad'


class Row(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cells: list[str]
    tone: Tone | None = None


class TableEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['table']
    seq: int = Field(..., ge=0)
    blockId: str
    columns: list[str]
    rows: list[Row]


class ProposalEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['proposal']
    seq: int = Field(..., ge=0)
    proposedChangeIds: list[UUID]


class NavigateEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['navigate']
    seq: int = Field(..., ge=0)
    href: str
    label: str


class SuggestionsEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['suggestions']
    seq: int = Field(..., ge=0)
    items: list[str]


class DoneEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['done']
    seq: int = Field(..., ge=0)


class ErrorEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['error']
    seq: int = Field(..., ge=0)
    message: str


class CitationEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['citation']
    seq: int = Field(..., ge=0)
    marker: str
    target: CitationTarget


class AgentEvent(
    RootModel[
        StepEvent
        | TextEvent
        | CitationEvent
        | TableEvent
        | ProposalEvent
        | NavigateEvent
        | SuggestionsEvent
        | DoneEvent
        | ErrorEvent
    ]
):
    root: (
        StepEvent
        | TextEvent
        | CitationEvent
        | TableEvent
        | ProposalEvent
        | NavigateEvent
        | SuggestionsEvent
        | DoneEvent
        | ErrorEvent
    ) = Field(
        ...,
        description='One server-sent event from an agent run. Emitted identically by the scenario agent (web) and the future LangGraph engine (Python).',
        title='AgentEvent',
    )
