# generated by datamodel-codegen:
#   filename:  agent-action.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ScheduleKind(StrEnum):
    pertemuan_klien = 'pertemuan_klien'
    penandatanganan = 'penandatanganan'
    internal = 'internal'


class ScheduleAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['schedule_form']
    widgetId: str
    berkasId: UUID
    date: str = Field(..., pattern='^\\d{4}-\\d{2}-\\d{2}$')
    time: str = Field(..., pattern='^\\d{2}:\\d{2}$')
    scheduleKind: ScheduleKind
    location: str | None = Field(None, max_length=200)
    title: str = Field(..., max_length=200, min_length=2)


class ChecklistAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['checklist_form']
    widgetId: str
    berkasId: UUID
    title: str = Field(..., max_length=200, min_length=2)
    dueDate: str | None = Field(None, pattern='^\\d{4}-\\d{2}-\\d{2}$')


class Then(StrEnum):
    schedule = 'schedule'
    summary = 'summary'
    kelengkapan = 'kelengkapan'
    readiness = 'readiness'


class PickBerkasAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['berkas_picker']
    widgetId: str
    berkasId: UUID
    then: Then
    text: str = Field(..., max_length=2000)


class Item(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str = Field(..., max_length=200, min_length=2)
    dueDate: str | None = Field(None, pattern='^\\d{4}-\\d{2}-\\d{2}$')


class ChecklistBatchAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['checklist_batch']
    widgetId: str
    berkasId: UUID
    items: list[Item] = Field(..., max_length=20, min_length=1)


class AgentAction(
    RootModel[
        ScheduleAction | ChecklistAction | PickBerkasAction | ChecklistBatchAction
    ]
):
    root: ScheduleAction | ChecklistAction | PickBerkasAction | ChecklistBatchAction = (
        Field(
            ...,
            description="The user's answer to a WidgetEvent, sent with the next message. Handled deterministically, never by a model.",
            title='AgentAction',
        )
    )
