# generated by datamodel-codegen:
#   filename:  agent-event.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Status(StrEnum):
    running = 'running'
    done = 'done'
    error = 'error'


class StepEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['step']
    seq: int = Field(..., ge=0)
    id: str
    label: str
    status: Status


class TextEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['text']
    seq: int = Field(..., ge=0)
    blockId: str
    delta: str
    unsupported: bool | None = Field(
        None,
        description='Claim without any valid citation; the UI flags it instead of hiding it.',
    )


class Kind(StrEnum):
    berkas = 'berkas'
    akta = 'akta'
    person = 'person'
    company = 'company'
    document = 'document'
    checklist = 'checklist'
    schedule = 'schedule'
    legal = 'legal'
    repertorium = 'repertorium'
    klapper = 'klapper'


class CitationTarget(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind
    id: UUID
    label: str
    href: str
    field: str | None = Field(
        None, description='Field to highlight, e.g. nik or address.'
    )


class Tone(StrEnum):
    ok = 'ok'
    warn = 'warn'
    bad = 'bad'


class Row(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cells: list[str]
    tone: Tone | None = None


class TableEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['table']
    seq: int = Field(..., ge=0)
    blockId: str
    columns: list[str]
    rows: list[Row]


class ProposalEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['proposal']
    seq: int = Field(..., ge=0)
    proposedChangeIds: list[UUID]


class NavigateEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['navigate']
    seq: int = Field(..., ge=0)
    href: str
    label: str


class SuggestionsEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['suggestions']
    seq: int = Field(..., ge=0)
    items: list[str]


class DoneEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['done']
    seq: int = Field(..., ge=0)


class ErrorEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['error']
    seq: int = Field(..., ge=0)
    message: str


class BerkasRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    title: str
    sub: str | None = None


class Kind1(StrEnum):
    pertemuan_klien = 'pertemuan_klien'
    penandatanganan = 'penandatanganan'
    internal = 'internal'


class Defaults(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date: str | None = Field(None, pattern='^\\d{4}-\\d{2}-\\d{2}$')
    time: str | None = Field(None, pattern='^\\d{2}:\\d{2}$')
    kind: Kind1 | None = None
    location: str | None = None
    title: str | None = None


class ScheduleFormWidget(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['schedule_form']
    berkas: BerkasRef | None = None
    berkasOptions: list[BerkasRef] | None = Field(None, max_length=20)
    defaults: Defaults


class Defaults1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str | None = None
    dueDate: str | None = Field(None, pattern='^\\d{4}-\\d{2}-\\d{2}$')


class ChecklistFormWidget(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['checklist_form']
    berkas: BerkasRef
    defaults: Defaults1


class Then(StrEnum):
    schedule = 'schedule'
    summary = 'summary'
    kelengkapan = 'kelengkapan'
    readiness = 'readiness'


class BerkasPickerWidget(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['berkas_picker']
    options: list[BerkasRef] = Field(..., max_length=20, min_length=1)
    then: Then
    text: str = Field(
        ..., description='The original request, continued after the choice.'
    )


class Item(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str
    dueDate: str | None = Field(None, pattern='^\\d{4}-\\d{2}-\\d{2}$')
    reason: str | None = None


class ChecklistBatchWidget(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['checklist_batch']
    berkas: BerkasRef
    items: list[Item] = Field(..., max_length=20, min_length=1)


class WidgetEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['widget']
    seq: int = Field(..., ge=0)
    widgetId: str
    widget: (
        ScheduleFormWidget
        | ChecklistFormWidget
        | BerkasPickerWidget
        | ChecklistBatchWidget
    )


class CitationEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['citation']
    seq: int = Field(..., ge=0)
    marker: str
    target: CitationTarget


class AgentEvent(
    RootModel[
        StepEvent
        | TextEvent
        | CitationEvent
        | TableEvent
        | ProposalEvent
        | NavigateEvent
        | SuggestionsEvent
        | WidgetEvent
        | DoneEvent
        | ErrorEvent
    ]
):
    root: (
        StepEvent
        | TextEvent
        | CitationEvent
        | TableEvent
        | ProposalEvent
        | NavigateEvent
        | SuggestionsEvent
        | WidgetEvent
        | DoneEvent
        | ErrorEvent
    ) = Field(
        ...,
        description='One server-sent event from an agent run. Emitted identically by the scenario agent (web) and the future LangGraph engine (Python).',
        title='AgentEvent',
    )
