# generated by datamodel-codegen:
#   filename:  principal.schema.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import BaseModel, ConfigDict


class Aal(StrEnum):
    aal1 = 'aal1'
    aal2 = 'aal2'


class AppRole(StrEnum):
    notaris = 'notaris'
    partner = 'partner'
    associate = 'associate'
    staf_admin = 'staf_admin'
    super_admin = 'super_admin'


class Principal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    user_id: UUID
    tenant_id: UUID | None = None
    app_role: AppRole | None = None
    aal: Aal
